apiVersion: skaffold/v2beta28
kind: Config
deploy:
  helm:
    releases:
      - name: tooljet
        remoteChart: tooljet
        repo: https://krzwiatrzyk.github.io/charts/
        createNamespace: true
        namespace: tooljet